### ISSUE TITLE
Feature Request: Add support for Windows agents

### ISSUE THREAD

**Issue by natemccurdy** [jorritfolmer/puppet-splunk#12]
This module looks great so far. But it'd be even better if there was support for installing Splunk on Windows. Specifically, installing universal forwarders on Windows.

Is that on the radar at all for this module @jorritfolmer ?

**Comment by jorritfolmer** [comment]
I've started working on supporting this in the `windows` brach, so this manifest will work:

```
node 'host16.testlab.local' {
  class { 'splunk':
    type   => 'uf',
    package_source => '//dc01/Company/splunkforwarder-6.5.1-f74036626f0c-x64-release.msi',
    tcpout => 'splunk.testlab.local:9997',
  }
}
```

Current status:
- Splunkforwarder get installed
- SSL stuff is being setup

However, it fails in the config because it appears Augeas isn't supported on Windows.
Because apparently these is no augeas library for Windows, which means there is no augeas gem for Puppet to use.

So for Windows we'll have to fall back to files and templates.
I'll look into that later.

**Comment by jorritfolmer** [comment]
For now I've disabled the augeas statements on Windows. See most recent commit.
This is ok for UniversalForwarder installations, so the manifest above works now.

**Comment by natemccurdy** [comment]
Wow, thanks for the fast turnaround @jorritfolmer !

I'll test this out soon and let you know if I can get it working in my environment.

In regards to there being no augeus on Windows, would [puppetlabs/inifile](https://forge.puppet.com/puppetlabs/inifile) work for managing the configs?
