### ISSUE TITLE
indexer_discovery:cluster miss configuration for UF and HF 

### ISSUE THREAD

**Issue by FlorinTar** [jorritfolmer/puppet-splunk#20]
It seems that while using index discover functionality in the file:
/opt/splunkforwarder/etc/apps/puppet_common_ssl_outputs/local/outputs.conf
it's adding the VM's hostname insted of the cluster master's one.
It does this for both UF and HF 

Example:
[indexer_discovery:cluster]
pass4SymmKey = somerandomkey
master_uri = https://uf.local:8089   # hostname should have been master.local instead.

class { 'splunk':
  type         => 'uf',
  ds           => $splunk_cm01,
  pass4symmkey => $splunk_pass4symmkey,
  tcpout       => 'indexer_discovery',
  admin        => {
    hash  => $splunk_admin_hash,
    fn    => 'Forwarder Administrator',
    email => $splunk_email,
  },
  service      => {
    ensure => running,
    enable => true,
  }

**Comment by jorritfolmer** [comment]
You do still have to specify a cluster master with `cm`. A UF will otherwise not know who to contact to discover the indexers.

If a `cm` statement is missing, the module will assume that this node is the cluster master itself since that is the only legitimate condition where a cluster master statement can be missing.

In the case of a UF howver, I'll start emitting a warning when `cm` is missing and indexer discovery is required since that is clearly an error condition.

**Comment by jorritfolmer** [comment]
Added explicit error message in v3.4.3, see commit a4e4af878bbbea1a3efa3ba334f5ddab7b1e8537

**Comment by FlorinTar** [comment]
Ok, that makes sense, thank you very much!

**Comment by FlorinTar** [comment]
I meant to close the case.
