### ISSUE TITLE
Splunk user directory permissions not working

### ISSUE THREAD

**Issue by dkangel37** [jorritfolmer/puppet-splunk#26]
Ok so the splunk uf is installed but the directory permissions need to be at least 755 for the splunk user to be able to start the service. Can you update the module to set the /opt/splunkforwarder directory to 755 for the splunk user? 

I tested it on linux and it works but it would be great if the module set it when it installs it automatically.

**Comment by jorritfolmer** [comment]
I'm not following. Splunk (Forwarder) gets installed from RPM, with the permissions and owner declared in the RPM. If I look at my various Splunk instances, both /opt/splunk, /opt/splunkforwarder and subdirs are splunk:splunk and 755, by default.

What flavour of Linux are you using, and what package manager?

**Comment by dkangel37** [comment]
Well once the install ran..root owned parts of the directory, such as /opt/splunkforwarder/var  and parts of the /etc directory as well. Running Redhat 7, running it through puppet enterprise using a yum repository

**Comment by jorritfolmer** [comment]
From the other issue it looks like you're using the subclasses individually.
You should just use the main splunk class, and fill the appropriate parameters like in one of the examples in the readme.

What I think is happening:
- splunk isn't set to boot-start as user splunk, because there are parameters lacking because splunk::install depends on there being setup properly, outside the splunk::installed subclass.
- once you start splunk, without this part being run properly, it will run as root, creating var/lib etc as root:root.

If you start with something like this and work from there, you'll be fine.
It installs Splunk UF, runs as user Splunk, pointing to a DS for further config:

```
node 'some-server.internal.corp.tld' {
  class { 'splunk':
    type => 'uf',
    ds   => 'splunk-server.internal.corp.tld:8089',
  }
}
```

**Comment by dkangel37** [comment]
Thanks. I added some of the notes for this in the other issue. 

I adjusted to use just the splunk class to run the install and ds setup.

- It's giving me an error on the Splunk::installed class saying it's missing the user even though the user is included within the main splunk class. 
- To make it run I had  to add the splunk::installed class and put the user option there. Then it fails because it can't enable splunk, This is due to the /opt/splunkforwarder/var  directory being owned by root for some reason. 

Current setting are below: (ignore the format --pulling it from the PE gui.
**splunk class:**
type | = | "uf" 
ds | = | "ds:8089" 
phonehomeintervalinsec | = | 60 
splunk_os_group | = | "splunk" 
package_source | = | "http://site/repo/splunk/products/universalforwarder/releases/7.0.2/linux/" 
version | = | "7.0.2"
splunk_os_user | = | "splunk"

**splunk::installed class**
splunk_os_user | = | "splunk"

**Comment by jorritfolmer** [comment]
I've never seen or used the PE GUI to be honest.
Can you share the installation steps you used to install PE and the Splunk module?
I'll try to reproduce your setup with a PE trial version.

**Comment by dkangel37** [comment]
So i've found the following:
Attempted the install with the instructions you provided on a clean test server. The splunk module worked well. The only thing now is that root owns some of the apps in "/etc/apps" namely all the puppet_common_* apps. Otherwise it works well. So basically i'll have to automate a chown, chmod 
 and splunkd restart within the RedHat environment to ensure that the splunk user owns everything. I doubt the issue is with your module at this point. 

Running PE version 2017.3.2..I don't have the install steps unfortunately, since i didn't set it up. I do know that it's a base install, nothing fancy..so you should be able to install it as RedHat states to reproduce this issue.

**Comment by jorritfolmer** [comment]
I can't reproduce the issue you're having with Puppet Enterprise.
After configuring through the PE GUI as per the screenshot below, 
Splunk runs as splunk, and everything in /opt/splunk is owned by splunk.

Perhaps you should remove the previous Splunk installation, /opt/splunk, /opt/splunkforwarder directory, and /etc/init.d/splunk. This removes previous misconfigured artifacts from when you used the splunk::installed class instead of the main splunk class.

Steps:
- I've created a node group with 1 single node.
- In the Configuration tab added the class "splunk".
- In the parameter section below filled the parameters like http_port etc:
- One Puppet run later, there is a working single instance Splunk:

<img width="818" alt="screen shot 2018-03-03 at 14 28 51" src="https://user-images.githubusercontent.com/11555154/36934850-04248932-1ef0-11e8-87b9-20d6847099ac.png">

**Comment by jorritfolmer** [comment]
I've added a section to example2b in the readme discussing Puppet Enterprise

**Comment by dkangel37** [comment]
Thanks this is great. I suspect it may be the test box i am on. I appreciate you testing it for me. I'll check out the new example2b.
