### ISSUE TITLE
Splunk_home parameter not found causes puppet run to fail

### ISSUE THREAD

**Issue by vidkun** [jorritfolmer/puppet-splunk#27]
Setting `splunk_home` parameter results in the following error during puppet run:

```Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Class[Splunk]: has no parameter named 'splunk_home' at /etc/puppetlabs/code/environments...```

Removing the `splunk_home` parameter results in a successful puppet run again.

**Comment by vidkun** [comment]
Looks like manifests/init.pp may just be missing the splunk_home param.

**Comment by jorritfolmer** [comment]
Thanks, that looks like a bug in the documentation.

Changing splunk_home is a bit of an issue, because:
- setting splunk_home should also install the splunk package into this directory, otherwise all the other manifests will fail, so adding splunk_home to init.pp won't work.
- only the rpm Puppet package provider supports relocating packages (afaict)
- but the rpm provider doesn't use repositories so you have to point to a URL where the actual Splunk rpm can be downloaded.

Another solution outside Splunk and Puppet would be to create bind mount (on Linux) that maps /opt/splunkforwarder to some other directory. From the outside Puppet and Splunk won't notice.

Does that work for you?

**Comment by vidkun** [comment]
It's not the cleanest solution, but it'll certainly work as a workaround for now. Thanks.
