### ISSUE TITLE
Is there reasoning behind NOT restarting the splunk deamon when the configuration changes?

### ISSUE THREAD

**Issue by bschonec** [jorritfolmer/puppet-splunk#49]
I've got about 2800 servers one which I'm going to be installing Splunk.  The initial roll-out will have those servers pointing to a beta-test environment and then to our real production environment.

If I change the splunk::ds parameter, the splunk daemon won't automatically restart.  The README.md makes note of this behavior.

What is the reasoning behind not restarting the splunk daemon?

**Comment by jorritfolmer** [comment]
Two things:

1. Safety: Splunk indexers in a cluster shouldn't be restarted by Puppet because your cluster will go down. Same for Search Head Clusters. 

2. Minimalism: only config the most enduring aspects of a Splunk installation: if it can be done through Splunk, use that.

Your use-case seems to involve Universal Forwarders that need to change from DS a to DS b. Safety doesn't really apply here because it doesn't involve core Splunk infra, and minimalism introduces weird hoops to jump through.

A workable solution is to include a "Notify" statement in manifests/deploymentclient.pp. This will make Splunk restart for every change to deploymentclient.conf, which seems to be what you're after. This would restart any Splunk instance that is configured with a DS, also non-UFs so you'd have to check if that is desirable. Probably a conditional check for type==uf would be a good idea.

Another, pure Splunkonic, way to migrate from DS a to DS b would be to create a new config app on the old deployment server that points to the new one. Just make sure the new config app is higher in the alphabet than the Puppet managed one.
